// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/ask_fasal_doctor.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var ask_fasal_doctor_default = defineTool({
  name: "ask_fasal_doctor",
  title: "Ask Fasal Doctor",
  description: "Ask Bharat AI's Fasal Doctor for structured crop diagnosis, pest / disease prescriptions (ICAR-standard), mandi advice, irrigation advice, or general Indian agriculture guidance. Returns a professional clinical report when the question is about a plant / crop.",
  inputSchema: {
    question: z.string().min(3).max(4e3).describe(
      "The farmer's question in English, Hindi, Hinglish or Marwadi. E.g. 'Wheat leaves turning yellow with orange stripes' or 'Aaj bajra ka mandi bhav Rajasthan'."
    ),
    lang: z.enum(["en", "hi", "hinglish", "mar"]).default("en").describe("Preferred reply language: en, hi (Hindi), hinglish, or mar (Marwadi).")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ question, lang }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const apiKey = process.env.LOVABLE_API_KEY;
    if (!apiKey) {
      return { content: [{ type: "text", text: "Service misconfigured: LOVABLE_API_KEY missing." }], isError: true };
    }
    const system = `You are Bharat AI - Fasal Doctor. Reply in language code: ${lang}.
For any crop disease, pest, deficiency or scan-style question, respond ONLY in this format:

\u{1F4CB} **FASAL DOCTOR - CLINICAL REPORT**

\u{1F33E} **1. Fasal Ka Vivaran (Crop Details)**
\u{1F52C} **2. Bimari Ka Diagnosis (Disease Identification)** \u2014 include severity \u{1F7E2}/\u{1F7E1}/\u{1F534} and cause type
\u{1F33F} **3. Dikhne Wale Lakshan (Observed Symptoms)** \u2014 bullets
\u{1F48A} **4. Doctor ki Parchi - Ilaaj aur Dawa** \u2014 Jaivik + Rasayanik (ICAR chemical name, dosage, method)
\u26A0\uFE0F **5. Savdhani aur Sujhav**

For non-plant / non-agri questions, answer briefly in bullet points. Never fabricate a disease for non-plant input; politely refuse instead.`;
    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Lovable-API-Key": apiKey,
        "X-Lovable-AIG-SDK": "mcp-js",
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: system },
          { role: "user", content: question }
        ]
      })
    });
    if (!res.ok) {
      const errText = await res.text();
      return {
        content: [{ type: "text", text: `AI gateway error ${res.status}: ${errText.slice(0, 300)}` }],
        isError: true
      };
    }
    const data = await res.json();
    const reply = data?.choices?.[0]?.message?.content ?? "No response generated.";
    return {
      content: [{ type: "text", text: reply }],
      structuredContent: { reply, lang, askedBy: ctx.getUserEmail() ?? ctx.getUserId() }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ctesglwdrufastiswuxr";
var mcp_default = defineMcp({
  name: "bharat-ai-fasal-doctor",
  title: "Bharat AI \xB7 Fasal Doctor",
  version: "0.1.0",
  instructions: "Bharat AI - an Indian agriculture assistant by Jaswant. Use `ask_fasal_doctor` to get structured ICAR-standard crop diagnosis, pest / disease prescriptions, mandi rate guidance, irrigation and fertilizer advice in English, Hindi, Hinglish or Marwadi.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [ask_fasal_doctor_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
